**Numpy provides a unified way to manage numerical arrays in Python

In [1]:
import numpy as np 

In [2]:
a=np.array([0],np.int16) #16-bit integer

In [3]:
a.itemsize #in 8-bit bytes

2

In [4]:
a.nbytes

2

In [5]:
a=np.array([0],np.int64) #64-bit integer
a.itemsize

8

In [6]:
b=np.array([0,1,2,23,4],np.int64) #64-bit integer
b.shape

(5,)

In [7]:
b.itemsize

8

In [8]:
a.nbytes

8

In [9]:
a=np.array([1,2])

In [10]:
a

array([1, 2])

In [11]:
#Note that you cannot tack on extra elements to a Numpy array after creation
a[2]=32

IndexError: index 2 is out of bounds for axis 0 with size 2

**This is because the block of memory has already been delineated and Numpy will
not allocate new memory and copy data without explicit instruction. Also, once you
create the array with a specific dtype, assigning to that array will cast to that type

In [12]:
#for example
x=np.array(range(5),dtype=int)

In [13]:
x[0]=1.33   # float assignment does not match dtype=int

In [14]:
x

array([1, 1, 2, 3, 4])

In [15]:
x[0]='this is a string'

ValueError: invalid literal for int() with base 10: 'this is a string'

**Multidimensional Arrays

In [16]:
a=np.array([[1,3],[4,5]]) #omitting dtypes picks default

In [17]:
a

array([[1, 3],
       [4, 5]])

In [18]:
a.dtype

dtype('int32')

In [19]:
a.shape

(2, 2)

In [20]:
a.nbytes

16

In [21]:
a.flatten()

array([1, 3, 4, 5])

In [22]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [24]:
a=np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
x,y=np.meshgrid([1,2,3],[5,6])

In [26]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [27]:
y

array([[5, 5, 5],
       [6, 6, 6]])

In [28]:
a=np.zeros((2,2))

In [29]:
a

array([[0., 0.],
       [0., 0.]])

In [30]:
#abs=> it gives the distance of a number from zero on the number line, regardless of the direction.
np.fromfunction(lambda i,j: abs(i-j)<=1,(4,4))

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [False,  True,  True,  True],
       [False, False,  True,  True]])

In [31]:
a=np.zeros((2,2), dtype=[('x','f4')])

In [32]:
a['x']

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [33]:
x=np.array([(1,2)], dtype=[('value','f4'),('amount','c8')])

In [34]:
x['value']

array([1.], dtype=float32)

In [35]:
x['amount']

array([2.+0.j], dtype=complex64)

**Reshaping and Stacking Numpy Arrays**

In [36]:
x=np.arange(5)
y=np.array([9,10,11,12,13])

In [37]:
np.hstack([x,y]) #stack horizontally

array([ 0,  1,  2,  3,  4,  9, 10, 11, 12, 13])

In [38]:
np.vstack([x,y]) #stack vertically

array([[ 0,  1,  2,  3,  4],
       [ 9, 10, 11, 12, 13]])

In [39]:
np.dstack([x,y])  #dstack method if you want to stack in the third depth dimension

array([[[ 0,  9],
        [ 1, 10],
        [ 2, 11],
        [ 3, 12],
        [ 4, 13]]])

Numpy np.concatenate handles the general arbitrary-dimension case. In some
codes (e.g., scikit-learn), you may find the terse np.c_ and np.r_ used to
stack arrays column-wise and row-wise:

In [40]:
np.c_[x,y]

array([[ 0,  9],
       [ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13]])

In [41]:
np.r_[x,y]

array([ 0,  1,  2,  3,  4,  9, 10, 11, 12, 13])

**Duplicating Numpy Arrays**

Numpy has a repeat function for duplicating elements and a more generalized
version in tile that lays out a block matrix of the specified shape,

In [42]:
x=np.arange(4)

In [43]:
np.repeat(x,2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [44]:
np.tile(x,(2,1))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [45]:
np.tile(x,(2,2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [46]:
#non-numerics
np.array(['a','b','cow','Gaurav','Anushka'])

array(['a', 'b', 'cow', 'Gaurav', 'Anushka'], dtype='<U7')

**Reshaping Numpy Arrays**

In [47]:
a=np.arange(10).reshape(2,5)

In [48]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
a.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
a.reshape(3,5)

ValueError: cannot reshape array of size 10 into shape (3,5)

In [51]:
a.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [52]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

for complex numbers we can use .H 
but i don't it won't wok here

In [53]:
# Complex matrix
a = np.array([[1+2j, 3-4j], [5+6j, 7-8j]])
a.conj().T

array([[1.-2.j, 5.-6.j],
       [3.+4.j, 7.+8.j]])

**Slicing, Logical Array Operations**

In [54]:
x=np.arange(50).reshape(5,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
x[:,0]  #any row ,0th column

array([ 0, 10, 20, 30, 40])

In [56]:
x[0,:] #any column, 0th row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x[1:3,4:6]

array([[14, 15],
       [24, 25]])

In [58]:
x=np.arange(50).reshape(5,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
x = np.arange(2*3*4).reshape(2,3,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
np.where(x%2==0)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2], dtype=int64))

In [61]:
x[np.where(x%2==0)]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [62]:
x[np.where(np.logical_and(x%2==0,x<9))]

array([0, 2, 4, 6, 8])

In [63]:
x[np.where(np.logical_or(x%2==0,x<9))]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 14, 16, 18, 20, 22])

In [64]:
 a=np.arange(9).reshape((3,3))

In [65]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
b=np.fromfunction(lambda i,j:abs(i-j) <=1,(3,3))
b

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [67]:
a[b]

array([0, 1, 3, 4, 5, 7, 8])

In [68]:
b=(a>4)
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [69]:
a[b]

array([5, 6, 7, 8])

**Slicing in NumPy:**

NumPy slicing usually creates views, not copies. Views are references to the original data, and modifying the view will affect the original array.
This behavior is different from regular Python lists, where slicing creates copies.


**Advanced Indexing:**

Advanced indexing in NumPy involves using arrays of indices or boolean masks to access elements.
When the indexing object is a non-tuple sequence, another NumPy array, or a tuple with at least one sequence or NumPy array, it may create copies. 

In [70]:
x=np.ones((3,3))

In [71]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
x[:,[0,1,2,2]]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
y=x[:,[0,1,2,2]]

In [74]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
y=x[:2,:2]

In [76]:
y

array([[1., 1.],
       [1., 1.]])

In [77]:
x[0,0]=99

In [78]:
x

array([[99.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [79]:
y

array([[99.,  1.],
       [ 1.,  1.]])

The first operation (y = x[:2, :2]) creates a view, and modifications to one affect the other.
because a view is just a window into the same memory:

The second operation (y = x[:, [0, 1, 2, 2]]) involves advanced indexing and creates a copy, so modifications to one do not affect the other.

Note that if you want to explicitly force a copy without any indexing tricks, you can
do y=x.copy(). The code below works through another example of advanced
indexing versus slicing:

In [80]:
import numpy as np

# Create an array
x = np.arange(5)

# Using slicing to create a view
y_slicing = x[:3]

# Using advanced indexing to create a copy
y_advanced_indexing = x[[0, 1, 2]]

# Using the copy method
y_explicit_copy = x.copy()

# Modify the original array
x[0] = 999

# Print the arrays
print("Original array (x):", x)
print("Sliced array (y_slicing):", y_slicing)
print("Advanced indexed array (y_advanced_indexing):", y_advanced_indexing)
print("Explicit copy array (y_explicit_copy):", y_explicit_copy)


Original array (x): [999   1   2   3   4]
Sliced array (y_slicing): [999   1   2]
Advanced indexed array (y_advanced_indexing): [0 1 2]
Explicit copy array (y_explicit_copy): [0 1 2 3 4]


**overlapping Numpy Arrays**

In [81]:
from numpy.lib.stride_tricks import as_strided
x=np.arange(16).astype(np.int32)
y=as_strided(x,(7,4),(8,4))
y

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15]])



Original Array x:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Strided Array y:

1. **Rows (along the first dimension):**
   - Starting at the first row (row 0), the initial element is 0.
   - To move to the next row (row 1), it jumps 8 bytes in memory (8 elements * 4 bytes per element).
   - Similarly, for subsequent rows, each row starts where the previous row left off, moving 8 bytes forward.

   | Row Index | Starting Element | Stride |
   |-----------|------------------|--------|
   | 0         | 0                | 8      |
   | 1         | 2                | 8      |
   | 2         | 4                | 8      |
   | 3         | 6                | 8      |
   | 4         | 8                | 8      |
   | 5         | 10               | 8      |
   | 6         | 12               | 8      |

2. **Columns (along the second dimension):**
   - Within each row, to move to the next column, it jumps 4 bytes in memory (4 bytes per element).

   | Column Index | Starting Element | Stride |
   |--------------|------------------|--------|
   | 0            | 0                | 4      |
   | 1            | 1                | 4      |
   | 2            | 2                | 4      |
   | 3            | 3                | 4      |

In summary, the `strides` parameter `(8, 4)` is responsible for creating overlapping blocks in the array `y`. The first dimension (rows) strides 8 bytes, creating overlapping rows, and the second dimension (columns) strides 4 bytes within each row. This results in an efficient representation of overlapping blocks without copying the original data.

In [82]:
x[::2]=99

In [83]:
x

array([99,  1, 99,  3, 99,  5, 99,  7, 99,  9, 99, 11, 99, 13, 99, 15])

In [84]:
y

array([[99,  1, 99,  3],
       [99,  3, 99,  5],
       [99,  5, 99,  7],
       [99,  7, 99,  9],
       [99,  9, 99, 11],
       [99, 11, 99, 13],
       [99, 13, 99, 15]])